services:
  dr-freud:
    build: .
    env_file: .env
    ports:
      - ${STREAMLIT_SERVER_PORT}:${STREAMLIT_SERVER_PORT}
    volumes:
      - .:/app
    networks:
      - proxy
    environment:  
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dr-freud-ssl.entrypoints=https"
      - "traefik.http.routers.dr-freud-ssl.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.dr-freud-ssl.tls=true"
      - "traefik.http.routers.dr-freud-ssl.tls.certresolver=http"
      - "traefik.http.routers.dr-freud-ssl.middlewares=default@file"
      - "traefik.http.routers.dr-freud-ssl.service=dr-freud-ssl"
      - "traefik.http.services.dr-freud-ssl.loadbalancer.server.port=${STREAMLIT_SERVER_PORT}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    name: proxy
    driver: bridge
    attachable: true
